# Site settings
title: Nitzan Farhi
email: nitzanfarhi@mail.tau.ac.il
description: Webpage of Nitzan Farhi\
baseurl: ""
url: ""

# Google analytics ID: Remove or use your own!
google_analytics: UA-43124730-2
google_analytics_4: G-ZKF0SXQQD6

# Footer info
about: >
    Nitzan Farhi<br/>
    School of Electrical Engineering, <a href="https://english.tau.ac.il" target="_blank">TAU</a><br/>
    Tel Aviv University


information: >
    <a href="mailto:nitzanfarhi@mail.tau.ac.il" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Nitzan via email</a> <br/>
    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use my site as a template!</a> <br/>
    <a href="/vacancies.html"><i class="fa fa-users fa-1x"></i> Explore openings</a>


coordinates: >
  Haim Levanon 30 St<br/>
  Tel Aviv, GA 69978 



# Pages shown in navbar
nav_pages:
  - name: publications
  - name: datasets
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll-scholar']

scholar:

  last_name: Farhi
  first_name: [Nitzan]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
